[project]
name = "codingagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ritam Karmakar", email = "ritamkarmakar61@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai==1.75.0",
    "python-dotenv==1.1.0",
]

[project.scripts]
codingagent = "codingagent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
